fix: set git config to global and check if env vars are set (#104)

diff --git a/.github/workflows/generate-api-types.yml b/.github/workflows/generate-api-types.yml
--- a/.github/workflows/generate-api-types.yml
+++ b/.github/workflows/generate-api-types.yml
@@ -21,8 +21,12 @@ jobs:
 
     - name: Configure Git
       run: |
-        git config --local user.name 'API types'
-        git config --local user.email ${API_TYPES_EMAIL}
+        if [ -z "${API_TYPES_EMAIL}" ]; then
+          echo "Error: API_TYPES_EMAIL is not set or empty."
+          exit 1
+        fi
+        git config --global user.name 'API types'
+        git config --global user.email ${API_TYPES_EMAIL}
 
     - name: Setup Python
       uses: actions/setup-python@v2
@@ -55,6 +59,10 @@ jobs:
 
     - name: Commit & Push changes
       run: |
+        if [ -z "${API_TYPES_PAT_TOKEN}" ]; then
+          echo "Error: API_TYPES_PAT_TOKEN is not set or empty."
+          exit 1
+        fi
         git add ./frontend/types/api-types-v1.d.ts
         git commit -m "feat: generated new API types"
         git push https://x-access-token:${API_TYPES_PAT_TOKEN}@github.com/jst-seminar-rostlab-tum/eutop-mediamind.git HEAD:master
